version: "3.3"
services:
  server:
    image: "fridgeimage"
    # network_mode: host
    volumes:
      - ./instruments:/app
      - /dev:/dev
      - ./drivers:/drivers
    ports:
      - "80:80"
    restart: always
    tty: true
    privileged: true
    stdin_open: true
    command: ["python3","instrument_server.py"]

  tempControl:
    image: "fridgeimage"
    #network_mode: host
    volumes:
      - ./tempControl:/app
      - /dev:/dev
      - ./drivers:/drivers
    restart: always
    tty: true
    privileged: true
    stdin_open: true
    command: ["python3","temp_server.py"]