#This file should ONLY reflect detectors that are currently hooked up, characterized, and working.
---
id: 2255 #Detector number
biasChannel: 1 #Channel from ls vsrc (starts at 0)
smaPort: 10 #Sma port
ttChannel: 1 #Channel on timetagger
compChannel: 2 #Channel on comparator (1 = A 2 = B)
iBias: 4 #Bias current (microamps)
rSeries: 100 #resistance of series resistor (kohm)
---
id: 284 
biasChannel: 0
smaPort: 2
ttChannel: 2
compChannel: 1
iBias: 5.5
rSeries: 200